config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'subscriptions/index'

  resources :subscriptions, only: :index do
    resources :orders, only: [:create]
  end

  resources :orders, only: :index do
    collection do
      get 'clean'
    end
  end

  root 'funds#index'
  get 'calendar/index'
  resources :funds

  get 'organizations/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :billings, only: [:index] do
    collection do
      get 'pre_payment'
      get 'execute'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    elsif user.premium?
      can :read, :all
    else
      can :read, :index
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/billing.rb
class Billing < ApplicationRecord
  belongs_to :user
  has_many :orders
end

app/models/fund.rb
class Fund < ApplicationRecord
  validates :institution, :name, :description, :amount, :start, :end, :url, presence: true
  validates :start, :end, presence: true
  after_create :find_tags
  require "google/cloud/language"
  has_many :fund_tags
  has_many :tags, through: :fund_tags
  accepts_nested_attributes_for :tags
  accepts_nested_attributes_for :fund_tags

  def title
    name
  end

  def find_tags
    language = Google::Cloud::Language.new({credentials: JSON.parse(ENV['GOOGLE_APPLICATION_CREDENTIALS'])})
    response = language.analyze_entities content: description, type: :PLAIN_TEXT, language: 'es'
    tags = response.to_h[:entities].map{|k| k[:name]}
    add_tags(tags)
  end

  def add_tags(tags = [])
    fund = self
    tags.each do |tag|
      tag = Tag.find_or_create_by(name: tag)
      FundTag.create(fund_id: fund.id, tag_id: tag.id)
    end
  end
end

app/models/fund_tag.rb
class FundTag < ApplicationRecord
  belongs_to :fund
  belongs_to :tag
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :subscription
  belongs_to :billing, optional: true

  scope :cart, -> {where(paid:false)}

  def self.get_total
    pluck("price * quantity").sum()
  end

  def self.created_by_day
   group_by_day(:created_at).count
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  belongs_to :user
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  has_many :orders
  has_many :users, through: :orders
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :fund_tags
  has_many :funds, through: :fund_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :organization
  has_many :orders
  has_many :subscriptions, through: :orders
  has_many :billings
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  protect_from_forgery except: :index
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_fund, only: [:show, :edit, :update, :destroy]

# GET /funds
# GET /funds.json
def index
  if params[:q].present?
    @funds = Tag.where('name like ?', "%#{params[:q]}%").first
    if @funds
    else
      render "index2.js.erb"
    end
  else
    @funds = Fund.all
  end
end

# GET /funds/1
# GET /funds/1.json
def show
end

# GET /funds/new
def new
  @fund = Fund.new
end

# GET /funds/1/edit
def edit
  if current_user.admin?
  else
    render 'show'
  end
end

# POST /funds
# POST /funds.json
def create
  @fund = Fund.new(fund_params)
  respond_to do |format|
    if @fund.save
      format.html { redirect_to @fund, notice: 'El fondo fue creado exitosamente.' }
      format.json { render :show, status: :created, location: @fund }
    else
      format.html { render :new }
      format.json { render json: @fund.errors, status: :unprocessable_entity }
    end
  end
end

# PATCH/PUT /funds/1
# PATCH/PUT /funds/1.json
def update
  respond_to do |format|
    if @fund.update(fund_params)
      @fund.tags << Tag.find(tag_params[:id]) if tag_params[:id] != ""
      flash.now[:notice] = "El fondo #{@fund.name} fue actualizado con éxito."
      format.html { redirect_to @fund }
      format.json { render :show, status: :ok, location: @fund }
      format.js
    else
      format.html { render :edit }
      format.json { render json: @fund.errors, status: :unprocessable_entity }
      format.js
    end
  end
end

# DELETE /funds/1
# DELETE /funds/1.json
def destroy
  @fund.destroy
  respond_to do |format|
    format.html { redirect_to funds_url, notice: 'Fund was successfully destroyed.' }
    format.json { head :no_content }
  end
end

private
# Use callbacks to share common setup or constraints between actions.
def set_fund
  @fund = Fund.find(params[:id])
end

# Never trust parameters from the scary internet, only allow the white list through.
def fund_params
  params.require(:fund).permit(:name, :institution, :description, :amount, :start, :end, :url, tag_ids:[])
end

def tag_params
  params.require(:fund).require(:tag).permit([:id])
end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    s = Subscription.find(params[:subscription_id])
    o = Order.find_or_create_by(user: current_user, subscription: s, paid: false, price: s.price)
    o.quantity += 1

    if o.save
      redirect_to orders_path, notice: "El plan fue agregado al carro."
    else
      redirect_to subscriptions_index_path, alert: "El plan NO fue agregado al carro."
    end
  end

  def clean
    @orders = Order.where(user: current_user, paid: false)
    @orders.destroy_all
    redirect_to orders_path, notice: 'El carro se ha vaciado.'
  end

  def index
    @orders = current_user.orders.cart
    @total = @orders.get_total
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billings_helper.rb
module BillingsHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <title>Grantsy</title>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css" integrity="sha384-5SOiIsAziJl6AWe0HWRKTXlfcSHKmYV4RBF18PPJ173Kzn7jzMyFuTtk8JA7QQG1" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/promise-polyfill@7.1.0/dist/promise.min.js"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render 'shared/navbar' %>
  <div class="flash">
    <%= render 'shared/alerts' %>
  </div>
  <div class="wrap">
    <%= yield %>
  </div>
  <%= render "shared/footer" %>
</body>
</html>

app/views/shared/_alerts.html.erb
<% if alert.present? %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<% end %>

<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

app/views/shared/_chart.html.erb
<%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
<% my_chart = Order.created_by_day %>

<%= column_chart my_chart %>

app/views/shared/_footer.html.erb
<footer class="footer bg-light">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
        <ul class="list-inline mb-2">
          <li class="list-inline-item">
            <a href="#">Acerca del sitio</a>
          </li>
          <li class="list-inline-item">&sdot;</li>
          <li class="list-inline-item">
            <a href="#">Contacto</a>
          </li>
        </ul>
        <p class="text-muted small mb-4 mb-lg-0">&copy; Plataforma de fondos 2018. Todos los derechos reservados.</p>
      </div>
      <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
        <ul class="list-inline mb-0">
          <li class="list-inline-item mr-3">
            <a href="#">
              <i class="fab fa-facebook fa-2x fa-fw"></i>
            </a>
          </li>
          <li class="list-inline-item mr-3">
            <a href="#">
              <i class="fab fa-twitter fa-2x fa-fw"></i>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#">
              <i class="fab fa-instagram fa-2x fa-fw"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_modal.html.erb
<div class="modal fade" id="modal-window" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="<%= funds_path%>">Grantsy</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <% if user_signed_in? %>
          <% if current_user.premium? %>
        <a class="nav-link" href="<%= calendar_index_path%>">Calendario</a>
        <% end %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= orders_path %>">Mi carro</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <%= "#{current_user.email}" %>
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="<%= edit_user_registration_path%>">Mi cuenta</a>
          <% if current_user.admin? %>
          <a class="dropdown-item" href="<%= admin_dashboard_path%>">Panel de admin</a>
          <% end %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="<%= destroy_user_session_path%>", data-method='DELETE'>Cerrar sesión <i class="icon-logout m-auto text-primary"></i></a>
        </div>
      </li>
    </ul>
    <% else %>
    <div>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_session_path%>">Log-in</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= new_user_registration_path %>">Registro</a>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>