config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'subscriptions/index'

  resources :subscriptions, only: :index do
    resources :orders, only: [:create]
  end

  resources :orders, only: :index do
    collection do
      get 'clean'
    end
  end

  root 'funds#index'
  get 'calendar/index'
  resources :funds

  get 'organizations/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :billings, only: [:index] do
    collection do
      get 'pre_payment'
      get 'execute'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :subscription
  belongs_to :billing, optional: true

  scope :cart, -> {where(paid:false)}

  def self.get_total
    pluck("price * quantity").sum()
  end

  def self.created_by_day
   group_by_day(:created_at).count
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    s = Subscription.find(params[:subscription_id])
    o = Order.find_or_create_by(user: current_user, subscription: s, paid: false, price: s.price)
    o.quantity += 1

    if o.save
      redirect_to orders_path, notice: "El plan fue agregado al carro."
    else
      redirect_to subscriptions_index_path, alert: "El plan NO fue agregado al carro."
    end
  end

  def clean
    @orders = Order.where(user: current_user, paid: false)
    @orders.destroy_all
    redirect_to orders_path, notice: 'El carro se ha vaciado.'
  end

  def index
    @orders = current_user.orders.cart
    @total = @orders.get_total
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<div class="container">
  <% if @orders.count > 0 %>
    <table class="table">
    <thead>
      <tr>
        <th>Plan</th>
        <th>Valor</th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td> <%= order.subscription.plan_name %> </td>
          <td> <%= order.price %></td>
        </tr>
      <% end %>
      <tr class="table-dark">
      <td><strong>Total de la compra:</strong></td>
      <td><strong><%= @total %></strong></td>
      </tr>
    </tbody>
  </table>

  <%= link_to 'Limpiar carro', clean_orders_path, class: 'btn btn-outline-danger' %>
  <%= link_to 'Confirmar compra', pre_payment_billings_path, class: 'btn btn-success float-right' %>

  <% else %>
    <div class="d-flex p-2 bd-highlight">No tienes planes en tu carro de compra.</div>
  <% end %>
</div>