config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'subscriptions/index'

  resources :subscriptions, only: :index do
    resources :orders, only: [:create]
  end

  resources :orders, only: :index do
    collection do
      get 'clean'
    end
  end

  root 'funds#index'
  get 'calendar/index'
  resources :funds

  get 'organizations/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :billings, only: [:index] do
    collection do
      get 'pre_payment'
      get 'execute'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  has_many :orders
  has_many :users, through: :orders
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
 skip_before_action :authenticate_user!, only: [:index]
 before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.fetch(:subscription, {})
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/index.html.erb
<section class="pricing-table">
  <div class="container">
    <div class="block-heading">
      <h2>Lista de planes</h2>
      <p>Inscríbete en nuestro plan premium y accede a nuestro buscador de fondos y calendario.</p>
    </div>
    <div class="row justify-content-md-center">
      <% @subscriptions.each do |subscription| %>
      <div class="col-md-5 col-lg-4">
        <div class="item">
          <% if subscription.plan_name == "6 meses" %>
            <div class="ribbon"> <%= "Best value" %> </div>
            <% end %>
          <div class="heading">
            <h3><%= subscription.plan_name %></h3>
          </div>
          <p><%= "Este es el plan de #{subscription.plan_name}."%></p>
          <div class="features">
            <h4><span class="feature">Duración</span> : <span class="value"><%= subscription.plan_name %></span></h4>
          </div>
          <div class="price">
            <h4>$<%= subscription.price %></h4>
          </div>
          <%= link_to "Comprar", subscription_orders_path(subscription), data: {toggle: "modal", target: "#modal-window"}, class: 'btn btn-outline-success btn-block', method: :post %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</section>

<%= render 'shared/modal' %>