config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'subscriptions/index'

  resources :subscriptions, only: :index do
    resources :orders, only: [:create]
  end

  resources :orders, only: :index do
    collection do
      get 'clean'
    end
  end

  root 'funds#index'
  get 'calendar/index'
  resources :funds

  get 'organizations/index'

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  resources :billings, only: [:index] do
    collection do
      get 'pre_payment'
      get 'execute'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fund.rb
class Fund < ApplicationRecord
  validates :institution, :name, :description, :amount, :start, :end, :url, presence: true
  validates :start, :end, presence: true
  after_create :find_tags
  require "google/cloud/language"
  has_many :fund_tags
  has_many :tags, through: :fund_tags
  accepts_nested_attributes_for :tags
  accepts_nested_attributes_for :fund_tags

  def title
    name
  end

  def find_tags
    language = Google::Cloud::Language.new({credentials: JSON.parse(ENV['GOOGLE_APPLICATION_CREDENTIALS'])})
    response = language.analyze_entities content: description, type: :PLAIN_TEXT, language: 'es'
    tags = response.to_h[:entities].map{|k| k[:name]}
    add_tags(tags)
  end

  def add_tags(tags = [])
    fund = self
    tags.each do |tag|
      tag = Tag.find_or_create_by(name: tag)
      FundTag.create(fund_id: fund.id, tag_id: tag.id)
    end
  end
end

app/controllers/funds_controller.rb
class FundsController < ApplicationController
  protect_from_forgery except: :index
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_fund, only: [:show, :edit, :update, :destroy]

# GET /funds
# GET /funds.json
def index
  if params[:q].present?
    @funds = Tag.where('name like ?', "%#{params[:q]}%").first
    if @funds
    else
      render "index2.js.erb"
    end
  else
    @funds = Fund.all
  end
end

# GET /funds/1
# GET /funds/1.json
def show
end

# GET /funds/new
def new
  @fund = Fund.new
end

# GET /funds/1/edit
def edit
  if current_user.admin?
  else
    render 'show'
  end
end

# POST /funds
# POST /funds.json
def create
  @fund = Fund.new(fund_params)
  respond_to do |format|
    if @fund.save
      format.html { redirect_to @fund, notice: 'El fondo fue creado exitosamente.' }
      format.json { render :show, status: :created, location: @fund }
    else
      format.html { render :new }
      format.json { render json: @fund.errors, status: :unprocessable_entity }
    end
  end
end

# PATCH/PUT /funds/1
# PATCH/PUT /funds/1.json
def update
  respond_to do |format|
    if @fund.update(fund_params)
      @fund.tags << Tag.find(tag_params[:id]) if tag_params[:id] != ""
      flash.now[:notice] = "El fondo #{@fund.name} fue actualizado con éxito."
      format.html { redirect_to @fund }
      format.json { render :show, status: :ok, location: @fund }
      format.js
    else
      format.html { render :edit }
      format.json { render json: @fund.errors, status: :unprocessable_entity }
      format.js
    end
  end
end

# DELETE /funds/1
# DELETE /funds/1.json
def destroy
  @fund.destroy
  respond_to do |format|
    format.html { redirect_to funds_url, notice: 'Fund was successfully destroyed.' }
    format.json { head :no_content }
  end
end

private
# Use callbacks to share common setup or constraints between actions.
def set_fund
  @fund = Fund.find(params[:id])
end

# Never trust parameters from the scary internet, only allow the white list through.
def fund_params
  params.require(:fund).permit(:name, :institution, :description, :amount, :start, :end, :url, tag_ids:[])
end

def tag_params
  params.require(:fund).require(:tag).permit([:id])
end
end

app/helpers/funds_helper.rb
module FundsHelper
end

app/views/funds/_form.html.erb
<%= form_with(model: @fund) do |form| %>
<% if @fund.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@fund.errors.count, "error") %> prohibited this fund from being saved:</h2>
  <ul>
    <% @fund.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="name">
  <%= form.label :nombre_del_fondo %><br/>
  <%= form.text_field :name %>
</div>

<div class="field">
  <%= form.label :institución %><br/>
  <%= form.text_field :institution %>
</div>

<div class="field">
  <%= form.label :descripción %><br/>
  <%= form.text_area :description, size: "55x5" %>
</div>

<div class="field">
  <%= form.label :comienzo_postulación %><br/>
  <%= form.date_field :start, id: 'fund_start' %>
</div>

<div class="field">
  <%= form.label :fin_postulación %><br/>
  <%= form.date_field :end, id: 'fund_end' %>
</div>

<div class= "field">
  <% form.label :tags %><br/>
  <%= form.collection_check_boxes :tag_ids, @fund.tags, :id, :name do |b|%>
  <div class="collection-check-box">
    <%= b.check_box %>
    <%= b.label %>
  </div>
<% end %>
</div>

<%= form.fields_for :tag do |form_tag| %>
<div class= "field">
  <% form_tag.label :select_tag %></div><br/>
  <%= form_tag.select(:id, Tag.all.collect{|t| [t.name, t.id]}, { :include_blank => 'No agregar tag' })%>
<% end %>
</div >

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/funds/_fund.html.erb
<tr>
  <td><%= link_to "#{fund.name}", fund %></td>
  <td><%= fund.institution %></td>
  <td><%= fund.description %></td>
  <td><%= fund.amount %></td>
  <td><%= l fund.start, format: :custom %></td>
  <td><%= l fund.end, format: :custom %></td>
</tr>

app/views/funds/_show.html.erb
<table class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Fondo</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">Nombre fondo</th>
        <td><%= @fund.name %></td>
      </tr>
      <tr>
        <th scope="row">Institución</th>
        <td><%= @fund.institution %></td>
      </tr>
      <tr>
        <th scope="row">Descripción</th>
        <td><%= @fund.description %></td>
      </tr>
      <tr>
        <th scope="row">Monto</th>
        <td><%= @fund.amount %></td>
      </tr>
      <tr>
        <th scope="row">Comienzo postulación</th>
        <td><%= l @fund.start, format: :custom %></td>
      </tr>
      <tr>
        <th scope="row">Término postulación</th>
        <td><%= l @fund.end, format: :custom %></td>
      </tr>
      <tr>
        <th scope="row">Sitio web</th>
        <td><%= @fund.url %></td>
      </tr>
      <tr>
        <% if current_user.admin? %>
        <th scope="row">Tags</th>
        <td>
          <form>
            <select multiple data-role>
              <% @fund.tags.each do |t| %>
              <option value="<%= t.name %>"><%= t.name %></option>
              <% end %>
              <% end %>
            </select>
          </form>
        </td>
      </tr>
    </tbody>
  </table>
</table>

app/views/funds/edit.html.erb
<h1>Editing Fund</h1>

<%= render 'form', event: @fund %>

<%= link_to 'Show', @fund %> |
<%= link_to 'Back', funds_path %>

app/views/funds/edit.js.erb
$(".modal-body").html("<%= j render 'form', event: @fund %>")
$(".modal").modal();

app/views/funds/index.html.erb
<header class="masthead text-white text-center">
  <div class="overlay"></div>
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <h1 class="mb-5">¡Bienvenido a Grantsy!</h1>
        <h2> En esta nueva plataforma, podrás encontrar los fondos que necesitas para financiar a tu organización. </h2>
      </div>
      <div class="col-md-10 col-lg-8 col-xl-7 mx-auto">
      </div>
    </div>
  </div>
</header>

<section class="features-icons bg-light text-center">
  <div class="container">
    <div class="row">
      <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
          <div class="features-icons-icon d-flex">
            <i class="icon-paypal m-auto text-primary"></i>
          </div>
          <h3>Suscripción con Paypal</h3>
          <p class="lead mb-0">Puedes acceder a nuestro servicio completo contratando alguno de nuestros planes.</p>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-5 mb-lg-0 mb-lg-3">
          <div class="features-icons-icon d-flex">
            <i class="icon-paper-plane m-auto text-primary"></i>
          </div>
          <h3>Fondos</h3>
          <p class="lead mb-0">Recibe noticias de fondos</p>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="features-icons-item mx-auto mb-0 mb-lg-3">
          <div class="features-icons-icon d-flex">
            <i class="icon-calendar m-auto text-primary"></i>
          </div>
          <h3>Calendario</h3>
          <p class="lead mb-0">Revisa los fondos en el calendario</p>
        </div>
      </div>
    </div>
  </div>
  <%= link_to "Ver planes", subscriptions_index_path, class: 'btn btn-primary btn-lg' %>
</section>

<% if user_signed_in? %>

<section class="call-to-action text-white text-center">
  <div class="overlay"></div>
  <div class="container">
    <div class="form-row">
      <div class="col-7 mx-auto">
        <h2 class="mb-4">Busca tu fondo</h2>
        <form action="<% funds_path %>">
          <input class="form-control" name="q">
        </form>
        <div class="spinner_funds">
          <i class="fas fa-spinner fa-pulse fa-3x"></i>
        </div>
      </div>
    </div>
  </div>
</section>
<div class="table-responsive-sm">
  <table id= "tablequery" class="table table-striped table-hover table-dark">
    <thead>
      <tr>
        <th scope="col">Nombre del fondo</th>
        <th scope="col">Institución</th>
        <th scope="col">Descripción</th>
        <th scope="col">Monto max entregado</th>
        <th scope="col">Inicio postulación</th>
        <th scope="col">Término postulación</th>
      </tr>
    </thead>
    <tbody id="funds">
    </tbody>
  </table>
</div>

<% else %>

<section class="call-to-action text-white text-center">
  <div class="overlay"></div>
  <div class="container">
    <div class="form-row">
      <div class="col-7 mx-auto">
        <h2 class="mb-4">Debes ser usuario premium para ver los fondos.</h2>
        <div>
          <%= link_to "Regístrate", new_user_registration_path, class: 'btn btn-success btn-lg btn-block' %>
        </div>
      </div>
    </div>
  </div>
</section>
<% end %>

app/views/funds/index.js.erb
$("#funds").html("<%= j render @funds.funds %>");

app/views/funds/index2.js.erb
$("#funds").html(`<tr><td colspan="6">No se pudo encontrar ningún fondo.</td></tr>`);

app/views/funds/new.html.erb
<div class="container-fluid">

<h1>Crear nuevo fondo</h1>

<%= render 'form', fund: @fund %>

<%= link_to 'Volver', funds_path, class: 'btn btn-success btn-lg' %>

</div>

app/views/funds/show.html.erb
<table class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Fondo</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">Nombre fondo</th>
        <td><%= @fund.name %></td>
      </tr>
      <tr>
        <th scope="row">Institución</th>
        <td><%= @fund.institution %></td>
      </tr>
      <tr>
        <th scope="row">Descripción</th>
        <td><%= @fund.description %></td>
      </tr>
      <tr>
        <th scope="row">Monto</th>
        <td><%= @fund.amount %></td>
      </tr>
      <tr>
        <th scope="row">Comienzo postulación</th>
        <td><%= l @fund.start, format: :custom %></td>
      </tr>
      <tr>
        <th scope="row">Término postulación</th>
        <td><%= l @fund.end, format: :custom %></td>
      </tr>
      <tr>
        <th scope="row">Sitio web</th>
        <td><%= @fund.url %></td>
      </tr>
      <tr>
        <% if current_user.admin? %>
        <th scope="row">Tags</th>
        <td>
          <form>
            <select multiple data-role>
              <% @fund.tags.each do |t| %>
              <option value="<%= t.name %>"><%= t.name %></option>
              <% end %>
              <% end %>
            </select>
          </form>
        </td>
      </tr>
    </tbody>
  </table>
</table>

<%= link_to 'Volver al menú', funds_path, class: 'btn btn-success' %>

app/views/funds/show.js.erb
$(".modal-body").html("<%= j render 'show', event: @fund %>")
$(".modal").modal();

app/views/funds/update.js.erb
$(".modal").modal("hide");
$("#calendar").fullCalendar("refetchEvents");
$('.flash').html("<%= j render 'shared/alerts', locals: {flash: flash} %>")